### ISSUE TITLE
Auto-configure ViewResolvers using ViewResolverRegistry

### ISSUE THREAD

**Issue by bclozel** [bclozel/spring-boot-web-reactive#31]

**Comment by danielfernandez** [comment]
Note this is currently needed in order to be able to use all the *goodies* in `ReactiveWebAutoConfiguration.WebReactiveConfig` (currently mainly SpringBoot-style static resource configuration, which is great :)) in Spring Web Reactive applications that need at least one `ViewResolver`.

The reason this is needed is that the possible workaround of making the application's own configuration class extend `ReactiveWebAutoConfiguration.WebReactiveConfig` cannot be applied because `ResourceHandlerRegistrationCustomizer` (needed at the constructor) is package-protected :(

**Comment by bclozel** [comment]
FYI, [SPR-14754](https://jira.spring.io/browse/SPR-14754) will add more flexible options for configuring web reactive. The starter will adapt to those changes and you won't have to wait for the starter to support all configuration options!
