### ISSUE TITLE
Issue with reactor and spring-core versions after upgrade to Boot 2.0.0

### ISSUE THREAD

**Issue by danielfernandez** [bclozel/spring-boot-web-reactive#36]
After the upgrade to depend on Spring Boot 2.0.0 (which solved my issue with RxJava, thanks), something seems wrong with the version of reactor being included.

I see [here](https://github.com/bclozel/spring-boot-web-reactive/blob/7c0862ba258376703de5c7184f0a7f6f1fd54c87/spring-boot-dependencies-web-reactive/pom.xml#L25-L26) that Reactor 3.0.2.RELEASE should be being used, but actually, the version of `reactor-netty` being used seems to pull Reactor 2.0.8.RELEASE:

````
[INFO] +- io.projectreactor.ipc:reactor-netty:jar:0.5.1.RELEASE:compile
[INFO] |  +- io.netty:netty-all:jar:4.1.5.Final:compile
[INFO] |  +- io.projectreactor.ipc:reactor-ipc:jar:0.5.1.RELEASE:compile
[INFO] |  \- io.projectreactor:reactor-core:jar:2.0.8.RELEASE:compile
[INFO] |     +- org.reactivestreams:reactive-streams:jar:1.0.0:compile
[INFO] |     \- org.slf4j:slf4j-api:jar:1.7.21:compile
```

...and 2.0.8 doesn't even have `Mono`, apparently :-(

Also, even if `spring.version` is set to `5.0.0.M2`, the `spring-boot-starter-test` artifact is pulling for version `5.0.0.BUILD-SNAPSHOT` of `spring-core`:

```
[INFO] \- org.springframework.boot:spring-boot-starter-test:jar:2.0.0.BUILD-SNAPSHOT:test
[INFO]   ...
[INFO]    +- org.springframework:spring-core:jar:5.0.0.BUILD-SNAPSHOT:compile
[INFO]    \- org.springframework:spring-test:jar:5.0.0.M2:test
```

**Comment by bclozel** [comment]
Hi @danielfernandez , thanks for this report.
Could you post your full `build.gradle` / `pom.xml`?

**Comment by danielfernandez** [comment]
Sure, it's here: https://github.com/danielfernandez/test-spring-boot-reactive-netty/blob/e06508ee4b0d412771b9d316bf7745f3df5de20b/pom.xml

Note this: https://github.com/danielfernandez/test-spring-boot-reactive-netty/blob/e06508ee4b0d412771b9d316bf7745f3df5de20b/pom.xml#L25-L27

**Comment by bclozel** [comment]
Indeed, the reactor version was already an issue previously and that's why we added version overrides in projects generated by start.spring.io.

We're in the process of updating all that and pretty soon, you'll be able to create projects on start.spring.io by selecting Boot 2.0.0 SNAPSHOT. In the generated projects, you'll still get: 

```xml
<reactor.version>3.0.2.RELEASE</reactor.version>
```

This should be the case until [SPR-14531](https://jira.spring.io/browse/SPR-14531) is resolved, since it's the last dependency on reactor 2.x.

Now about the Spring `5.0.0.M2` version, this is my fault, it doesn't make sense to build against that since Boot 2.0 is building against 5.0.0 SNAPSHOT. I'll fix those versions right away.

**Comment by danielfernandez** [comment]
Great, thanks Brian.
